sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip3 install coala
  - pip3 install coala-bears
install:
  - pip install -r requirements.txt
script:
  - nosetests  --with-coverage --exe --cover-package=walnut
  - coala --non-interactive
