sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install pep8
install:
  - pip install -r requirements.txt
script:
  - nosetests  --with-coverage --exe --cover-package=walnut
  - find . -name \*.py -exec pep8 --ignore=E501 {} +
