sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip3 install coala
  - pip3 install coala-bears
script: nosetests  --with-coverage --exe --cover-package=walnut
