sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip3 install virtualenv
  - pip3 install -r requirements.txt
install:
  - virtualenv wAlnut_environment
  - source wAlnut_environment/bin/activate
script: nosetests --exe -s
